### PR TITLE
Fix minor issues

### PR DESCRIPTION
**Pull request by hs536**
Fix minor issues. Some of these causes the build to fail without Eclipse repository.

### CODE REVIEW

**Comment by arjantijms** [comment]
Note that jsf template doesn't work with Faces 4, and we should maybe consider retiring it.

**Comment by hs536** [comment]
That's shocking news... We need to deal with it in the near future, but this PR just corrects the current state of master branch.

**Comment by arjantijms** [comment]
> That's shocking news...

The question is how to best handle it. I've mentioned it before, and one of the suggestions was to ship GF without a graphical admin console. 

Another option is to develop a new admin console from scratch using normal Faces and probably PrimeFaces. That's technically the best option probably, but it would need some funding and collaboration. It's unlikely random volunteers from the community will put together a complete new admin console.

We could also drag jSFtemplate again further. Maybe it's doable, though technically... questionable. JSF Template was, IMHO, already pulled from the 2000's against its wishes into the 2010's. Do we really want to try to pull it into the 2020's? I'm not sure.

**Review by arjantijms — APPROVED** [review]

**Comment by hs536** [comment]
I think we should create a admin console based on the current Jakarta Faces as well. current management console is very difficult even to debug.. I've tried to create a small one in my private time, but the question of what is the best way to design and develop it makes me pause...

**Comment by ggam** [comment]
The admin console was indeed a very useful tool at its time, but I'm not sure it's that useful now in the age of containers.

I might be totally wrong on this, but I think the administrative functionality is already exposed as REST services. If that's the case, another option would be to create a thin JavaScript UI with just the basic funcionality, specially for viewing the configuration.

In my experience, once the server is configured (which you can easily do with the CLI too), what you usually need is to be able to see what's deployed. Interestingly, you can now see JDBC pools created from at server level (domain.xml) but not the ones defined at application level via annotations or web.xml. The same happens with other resources and will be more important as, for example, concurrency artifacts are deployed from the application.

Being able to see the whole configuration of all created resources in a UI might well be more useful than the complete admin console.

PS: IBM recently open sourced and included the Liberty admin console in OpenLiberty, which has very limited configuration funcionality. See https://openliberty.io/docs/21.0.0.12/admin-center.html

**Comment by ggam** [comment]
One point I forgot about the admin console and REST... as long as there are REST endpoints, they can be exposed via OpenAPI so the need for a full blown GUI is reduced too. Anyone can create their own from the schema.

**Pull request merged**
